window.KIN_APP_CONFIG = {
  siteBaseUrl: "https://www.rox-experiences.com",
  servicesPageUrl: "https://www.rox-experiences.com/terapias-holisticas/",
  sessionPageUrl: "https://www.rox-experiences.com/astrologia-maya-tzolkin/",
  sessionBookingUrl: "https://wa.me/5491169047724",
  kinImageBasePath: "",
  sealImageBasePath: "./assets/seals",
  sealImages: {
    Dragon: "./assets/seals-import/Dragon.jpg",
    Wind: "./assets/seals-import/Wind.jpg",
    Night: "./assets/seals-import/Night.jpg",
    Seed: "./assets/seals-import/Seed.jpeg",
    Serpent: "./assets/seals-import/Serpent.jpg",
    Worldbridger: "./assets/seals-import/Worldbridger.jpg",
    Hand: "./assets/seals-import/Hand.jpg",
    Star: "./assets/seals-import/Star.jpg",
    Moon: "./assets/seals-import/Moon.jpg",
    Dog: "./assets/seals-import/Dog.jpg",
    Monkey: "./assets/seals-import/Monkey.jpg",
    Human: "./assets/seals-import/Human.jpg",
    Skywalker: "./assets/seals-import/Skywalker.jpg",
    Wizard: "./assets/seals-import/Wizard.jpg",
    Eagle: "./assets/seals-import/Eagle.jpg",
    Warrior: "./assets/seals-import/Warrior.jpg",
    Earth: "./assets/seals-import/Earth.jpg",
    Mirror: "./assets/seals-import/Mirror.jpg",
    Storm: "./assets/seals-import/Storm.jpg",
    Sun: "./assets/seals-import/Sun.jpg",
  },
};
