window.KIN_APP_CONFIG = {
  shopBaseUrl: "https://www.rox-experiences.com",
  defaultShopUrl: "https://www.rox-experiences.com/productos/",
  sessionPageUrl: "https://www.rox-experiences.com/astrologia-maya-tzolkin/",
  sessionBookingUrl: "https://wa.me/541169047724",
  collections: {
    Dragon: "/productos/",
    Wind: "/productos/",
    Night: "/productos/",
    Seed: "/productos/",
    Serpent: "/productos/",
    Worldbridger: "/productos/",
    Hand: "/productos/",
    Star: "/productos/",
    Moon: "/productos/",
    Dog: "/productos/",
    Monkey: "/productos/",
    Human: "/productos/",
    Skywalker: "/productos/",
    Wizard: "/productos/",
    Eagle: "/productos/",
    Warrior: "/productos/",
    Earth: "/productos/",
    Mirror: "/productos/",
    Storm: "/productos/",
    Sun: "/productos/",
  },
};
